env:
  browser: true
  es2021: true
  jest: true
extends:
  - airbnb-base
  - plugin:import/recommended
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {
  'import/extensions': ['error', 'always', {
    js: 'always',
  }],
  'no-param-reassign': ['error', { 'props': false }]
}
  
