env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  - plugin:import/recommended
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {
  'import/extensions': ['error', 'always', {
    js: 'always',
  }]
}
  
